services:
  app:
    build: .
    container_name: backend
    # Uncomment for network discover availability
    # ports:
    #   - "3000:3000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/YOUR_COLLECTION_NAME
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cf-tunnel
    restart: unless-stopped
    depends_on:
      - app
    command: tunnel --no-autoupdate run --token YOUR_TOKEN

volumes:
  mongo-data: